# Generated by Django 3.1.4 on 2021-01-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210112_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='overview',
            new_name='f_para',
        ),
        migrations.AddField(
            model_name='post',
            name='s_para',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='t_para',
            field=models.TextField(blank=True, null=True),
        ),
    ]
