# Generated by Django 3.1.4 on 2021-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210112_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='af_link',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='bf_link',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='s_para',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='t_para',
            field=models.TextField(null=True),
        ),
    ]
