# Generated by Django 3.1.4 on 2021-01-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210113_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='f_para',
            new_name='overview',
        ),
        migrations.RemoveField(
            model_name='post',
            name='s_para',
        ),
        migrations.RemoveField(
            model_name='post',
            name='t_para',
        ),
        migrations.AlterField(
            model_name='post',
            name='af_link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='bf_link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
